In [ ]:
# Impact of RAM Capacity on Smartphone Pricing

## Statistical and Multiple Linear Regression Analysis

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\Aditya\Desktop\Stats Project\smartphones.csv')

df.head()

,smartphone_brand,model,price_inr,rating_score,processor_name,processor_brand,core_count,clock_speed_ghz,ram_gb,storage_gb,...,battery_mah,fast_charging,charging_watt,rear_camera_count,front_camera_count,rear_camera_main_mp,front_camera_main_mp,os_name,memory_card_supported,memory_card_type
0,blackzone,BlackZone S25 Ultra Maxx,8999,63,unisoc sc9863a1,unisoc,8,1.6,8,128,...,5000,False,10.0,1,1,32.0,16.0,android,NaN,NaN
1,ringme,Ringme Bold P70,5800,44,mediatek helio,mediatek,2,1.3,4,128,...,3260,False,10.0,1,0,13.0,NaN,android,NaN,NaN
2,lava,Lava Shark 5G (4GB RAM + 128GB),8998,60,unisoc t765,unisoc,8,2.3,4,128,...,5000,True,10.0,1,1,13.0,5.0,android,True,dedicated
3,vivo,Vivo Y19s 5G (4GB RAM + 128GB),11999,69,mediatek dimensity 6300,mediatek,8,2.4,4,128,...,6000,True,15.0,2,1,13.0,5.0,android,True,dedicated
4,vivo,Vivo Y19s 5G (4GB RAM + 64GB),10999,68,mediatek dimensity 6300,mediatek,8,2.4,4,64,...,6000,True,15.0,2,1,13.0,5.0,android,True,dedicated

In [7]:
df.shape

(758, 27)

In [8]:
df.columns

Index(['smartphone_brand', 'model', 'price_inr', 'rating_score',
       'processor_name', 'processor_brand', 'core_count', 'clock_speed_ghz',
       'ram_gb', 'storage_gb', 'has_5g', 'has_nfc', 'has_ir_blaster',
       'display_inches', 'res_width_px', 'res_height_px', 'refresh_rate_hz',
       'battery_mah', 'fast_charging', 'charging_watt', 'rear_camera_count',
       'front_camera_count', 'rear_camera_main_mp', 'front_camera_main_mp',
       'os_name', 'memory_card_supported', 'memory_card_type'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 758 entries, 0 to 757
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   smartphone_brand       758 non-null    object
 1   model                  758 non-null    object
 2   price_inr              758 non-null    int64
 3   rating_score           758 non-null    int64
 4   processor_name         758 non-null    object
 5   processor_brand        758 non-null    object
 6   core_count             758 non-null    int64
 7   clock_speed_ghz        758 non-null    float64
 8   ram_gb                 758 non-null    int64
 9   storage_gb             758 non-null    int64
 10  has_5g                 758 non-null    bool
 11  has_nfc                758 non-null    bool
 12  has_ir_blaster         758 non-null    bool
 13  display_inches         758 non-null    float64
 14  res_width_px           758 non-null    int64
 15  res_height_px          758 non-null    int64
 16  refresh_rate_hz        758 non-null    int64
 17  battery_mah            758 non-null    int64
 18  fast_charging          758 non-null    bool
 19  charging_watt          758 non-null    float64
 20  rear_camera_count      758 non-null    int64
 21  front_camera_count     758 non-null    int64
 22  rear_camera_main_mp    758 non-null    float64
 23  front_camera_main_mp   753 non-null    float64
 24  os_name                758 non-null    object
 25  memory_card_supported  551 non-null    object
 26  memory_card_type       551 non-null    object
dtypes: bool(4), float64(5), int64(11), object(7)
memory usage: 139.3+ KB

In [10]:
df.describe(include="all")

,smartphone_brand,model,price_inr,rating_score,processor_name,processor_brand,core_count,clock_speed_ghz,ram_gb,storage_gb,...,battery_mah,fast_charging,charging_watt,rear_camera_count,front_camera_count,rear_camera_main_mp,front_camera_main_mp,os_name,memory_card_supported,memory_card_type
count,758,758,758.000000,758.000000,758,758,758.000000,758.000000,758.000000,758.000000,...,758.000000,758,758.000000,758.000000,758.000000,758.000000,753.000000,758,551,551
unique,26,758,NaN,NaN,125,6,NaN,NaN,NaN,NaN,...,NaN,2,NaN,NaN,NaN,NaN,NaN,2,2,2
top,realme,BlackZone S25 Ultra Maxx,NaN,NaN,mediatek dimensity 6300,mediatek,NaN,NaN,NaN,NaN,...,NaN,True,NaN,NaN,NaN,NaN,NaN,android,True,dedicated
freq,134,1,NaN,NaN,117,388,NaN,NaN,NaN,NaN,...,NaN,746,NaN,NaN,NaN,NaN,NaN,730,383,326
mean,NaN,NaN,29424.088391,78.587071,NaN,NaN,7.906332,2.597889,7.990765,220.496042,...,5373.569921,NaN,45.982850,2.110818,1.015831,52.234828,19.446879,NaN,NaN,NaN
std,NaN,NaN,32989.687389,8.372894,NaN,NaN,0.701338,0.596162,3.134361,168.366358,...,980.222628,NaN,28.744416,0.707285,0.169738,26.662235,14.483133,NaN,NaN,NaN
min,NaN,NaN,4040.000000,37.000000,NaN,NaN,1.000000,1.000000,2.000000,32.000000,...,2000.000000,NaN,5.000000,1.000000,0.000000,8.000000,5.000000,NaN,NaN,NaN
25%,NaN,NaN,11857.250000,74.000000,NaN,NaN,8.000000,2.300000,6.000000,128.000000,...,5000.000000,NaN,25.000000,2.000000,1.000000,50.000000,8.000000,NaN,NaN,NaN
50%,NaN,NaN,18999.000000,80.000000,NaN,NaN,8.000000,2.400000,8.000000,128.000000,...,5000.000000,NaN,44.000000,2.000000,1.000000,50.000000,13.000000,NaN,NaN,NaN
75%,NaN,NaN,29990.000000,84.000000,NaN,NaN,8.000000,2.800000,8.000000,256.000000,...,6000.000000,NaN,68.000000,3.000000,1.000000,50.000000,32.000000,NaN,NaN,NaN
max,NaN,NaN,229900.000000,97.000000,NaN,NaN,10.000000,4.470000,24.000000,2048.000000,...,21200.000000,NaN,125.000000,3.000000,2.000000,200.000000,50.000000,NaN,NaN,NaN